name: Git Clone, Unzip, Install, and Run

on:
  push:
    branches:
      - main  # Jalankan setiap ada push di branch 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Clone the target repository
    - name: Clone noxcv repository
      run: |
        git clone https://github.com/TanakaDomp/LilyWa.git

    # Step 2: Navigate into the LilyWa directory
    - name: Change directory to LilyWa
      run: cd LilyWa

    # Step 3: Unzip lilybot.zip file inside the LilyWa folder
    - name: Unzip lilybot.zip
      run: |
        sudo apt-get install unzip  # Install unzip tool if not already installed
        unzip LilyWa/lilybot.zip -d ./noxcv  # Unzip lilybot.zip in the noxcv directory

    # Step 4: Install npm dependencies
    - name: Install npm dependencies
      run: |
        cd LilyWa
        npm install

    # Step 5: Start the npm application
    - name: Start the application
      run: |
        cd LilyWa
        npm start
